%% getOptimalInputUsingKriging
% Get optimal input values which maximize Kriging output generated by
% in-/output pairs
%
function [opt_inputs, varargout]= getOptimalInputUsingKriging(minmax, inputs, outputs, ...
                                                 LB, UB, varargin)
%% Release: 0.4

%%

error( nargchk(5, 6, nargin, 'struct') );
error( nargoutchk(0, 2, nargout, 'struct') );

%%

if nargin >= 6 && ~isempty(varargin{1})
  opt_method= varargin{1};
else
  % 
  opt_method= 'SMS-EMOA';
end

%%

models= cell(size(outputs, 2), 1);

for icol= 1:size(outputs, 2)
  
  [X, Y, Z, Fitness, models{icol, 1}]= evaluate_kriging(inputs, outputs(:, icol), 1);

end

%%

[opt_inputs, varargout]= optimizeKrigingOutput(minmax, models, LB, UB, opt_method);

%%


