%% getInstallDocOfToolbox
% Returns the documentation to install a toolbox, as is visualized in html
% help file
%
function installDoc= getInstallDocOfToolbox(toolbox)
%% Release: 1.3

%%

error( nargchk(1, 1, nargin, 'struct') );
error( nargoutchk(0, 1, nargout, 'struct') );

%%
% check arguments

checkArgument(toolbox, 'toolbox', 'gecoc_tool', '1st');


%%

toolName= toolbox.getToolboxName();
toolID=   toolbox.getToolboxID();


%%

installDoc= ...
  { '%% Installation', ...
    '%', ...
    sprintf('%% # Unzip the zip-file |%s.zip|, containing the ', toolID), ...
    sprintf('%% ''%s'' toolbox, to a folder of your choice. ', toolName), ...
    '% A particular good choice would be the toolbox folder of your MATLAB', ...
    '% installation. The path to this folder could be something like ', ...
    '% |C:/Programme/MATLAB/R2009a/toolbox|. To find out where MATLAB is ', ...
    '% installed, start MATLAB and type |matlabroot| (see: ', ...
    '% <matlab:doc(''matlabroot'') doc/matlabroot>. Create a folder in this path,', ...
    sprintf('%% e.g. named |%s|, and extract the zipped file there.', toolID), ...
    '% # Start MATLAB. In the text field _Current Folder_ or _Current', ...
    '% Directory_ (depends on the MATLAB version) choose the path to the', ...
    sprintf('%% folder you just created, here e.g.: |C:/Programme/MATLAB/R2009a/toolbox/%s/%s|.', ...
    toolID, toolID), ...
    '% # In the _Command Window_ type the command', ...
    sprintf('%% <matlab:doc(''%s/install_%s'') |install_%s()|>', ...
            toolID, toolID, toolID), ...
    sprintf('%% and confirm by pressing |Enter| to install the _%s_', toolName), ...
    '% Toolbox. If the installation was successful, then you get a message such as', ...
    sprintf('%% |The toolbox ''%s'' was installed successfully.|. ', toolName), ...
    '% If you got an error first make sure, whether the file ', ...
    sprintf('%%''install_%s.p'' or ''install_%s.m'' exists in the current folder. ', ...
    toolID, toolID), ...
    'For further help contact the developer: daniel.gaida@fh-koeln.de. ', ...
    '', ...
    sprintf('setup_%s()', toolID), ...
    '', ...
    '' }';

%%



%%


