%% replaceToolboxTagByText
% Replace tags in doc file such as the AuthorTag
%
function replaceToolboxTagByText(file)
%% Release: 1.3
% Copyright (C) 2014  Daniel Gaida

%%

error( nargchk(1, 1, nargin, 'struct') );
error( nargoutchk(0, 0, nargout, 'struct') );

%%
% check arguments

checkArgument(file, 'file', 'char', '1st');


%%
% get doc file in case script file was given

file= getDocFileOfFunction(file); 
        
%% 

replaceinfile( '%% <<AuthorTag_DG/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<AuthorTag_ALSB/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% André Luis Sousa Brito, M.Eng. Automation & IT\\n%%\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<AuthorTag_CW/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% Dipl.-Ing. Christian Wolf\\n%%\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<AuthorTag_CE/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% Dipl.-Ing. Christian Etzkorn\\n%%\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<AuthorTag_AKV/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% Ashwin Kumar Venkatesan, M.Eng. Automation & IT\\n%%\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<AuthorTag_ALSB_AKV/>>', ...
               sprintf(['%%%% Author\\n', ...
               '%% André Luis Sousa Brito, M.Eng. Automation & IT\\n%%\\n', ...
               '%% Ashwin Kumar Venkatesan, M.Eng. Automation & IT\\n%%\\n', ...
               '%% Daniel Gaida, M.Sc.EE.IT\\n%%\\n', ...
               '%% Cologne University of Applied Sciences (Campus Gummersbach)\\n%%\\n', ...
               '%% Department of Automation & Industrial IT\\n%%\\n', ...
               '%% GECO-C Group\\n%%\\n', ...
               '%% daniel.gaida@fh-koeln.de\\n%%\\n', ...
               '%% Copyright (C) 2009-%s\\n%%\\n', ...
               '%% Last Update: %s\\n', ...
               '%%'], ...
               datestr(now, 'yyyy'), ...
               getDateLastChangeOfScript(getScriptFileOfFunction(file)) ...
               ), file, '-nobak');

%%

replaceinfile( '%% <<plant/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |plant| : see <matlab:docsearch(''Definition,of,plant'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<plant_id/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |plant_id| : see <matlab:docsearch(''Definition,of,plant_id'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<substrate/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |substrate| : see <matlab:docsearch(''Definition,of,substrate'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<plant_network/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |plant_network| : see <matlab:docsearch(''Definition,of,plant_network'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<substrate_network/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |substrate_network| : see <matlab:docsearch(''Definition,of,substrate_network'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<plant_network_min/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |plant_network_min| : see <matlab:docsearch(''Definition,of,plant_network_min'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<plant_network_max/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |plant_network_max| : see <matlab:docsearch(''Definition,of,plant_network_max'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<substrate_network_min/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |substrate_network_min| : see <matlab:docsearch(''Definition,of,substrate_network_min'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<substrate_network_max/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |substrate_network_max| : see <matlab:docsearch(''Definition,of,substrate_network_max'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<digester_state_min/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |digester_state_min| : see <matlab:docsearch(''Definition,of,digester_state_min'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<digester_state_max/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |digester_state_max| : see <matlab:docsearch(''Definition,of,digester_state_max'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<equilibrium/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |equilibrium| : see <matlab:docsearch(''Definition,of,equilibrium'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<sensors/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |sensors| : see <matlab:docsearch(''Definition,of,sensors'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<initstate/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |initstate| : see <matlab:docsearch(''Definition,of,initstate'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<fitness_params/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |fitness_params| : see <matlab:docsearch(''Definition,of,fitness_params'') here>\\n', ...
               '%%']), file, '-nobak');

%%

replaceinfile( '%% <<opt_method/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |method| : see <matlab:docsearch(''Definition,of,optimization,method'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<pop_size/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |pop_size| : see <matlab:docsearch(''Definition,of,population,size'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<nGenerations/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |nGenerations| : see <matlab:docsearch(''Definition,of,number,of,generations'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<parallel/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |parallel| : see <matlab:docsearch(''Definition,of,parallel,operating,mode'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<nWorker/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |nWorker| : see <matlab:docsearch(''Definition,of,number,of,worker'') here>\\n', ...
               '%%']), file, '-nobak');

%%

replaceinfile( '%% <<pred_horizon/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |timespan| : see <matlab:docsearch(''Definition,of,prediction,horizon'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<control_horizon/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |control_horizon| : see <matlab:docsearch(''Definition,of,control,horizon'') here>\\n', ...
               '%%']), file, '-nobak');

replaceinfile( '%% <<delta/>>', ...
               sprintf(['%%%% \\n', ...
               '%% @param |delta| : see <matlab:docsearch(''Definition,of,control,sampling,time'') here>\\n', ...
               '%%']), file, '-nobak');

%%


