%% cmdEditBHKWs_Callback
% Callback of button cmdEditBHKWs of <gui_plant.html |gui_plant|>
%
function cmdEditBHKWs_Callback(hObject, eventdata, handles)
%% Release: 1.8

% hObject    handle to cmdEditBHKWs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

%%

error( nargchk(3, 3, nargin, 'struct') );
error( nargoutchk(0, 0, nargout, 'struct') );

%%

checkArgument(handles, 'handles', 'struct', '3rd');

%%
%get selected BHKW
handles.b_id_active= get(handles.listPlants, 'value');
handles.b_id_select= ...
    char(handles.workspace.plant.getCHPID(handles.b_id_active));
  
%%  
%prevent change of bhkw or fermenter during editing
handles= gui_plant_enable_elements(handles, 'off');    


%%

pos_frmPlC= get(handles.frmPlantControl, 'Position');

y_offset= 11.05;

if ~isfield(handles, 'frame1_bhkw')
  %create Frame for BHKW variables
  handles.frame1_bhkw= uipanel('Title', 'Edit BHKWs', ...
    'units', 'characters', ...
    'Position', [57.8 pos_frmPlC(2) 76.2 pos_frmPlC(4)]);
end

set(handles.frame1_bhkw,'Visible','on');

%texts
handles.btext.bID= uicontrol('Style', 'Text', 'String','BHKW ID:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 18.5 + y_offset 15 1.6153],'HandleVisibility','on', ...
    'parent', handles.frame1_bhkw);
handles.btext.bname= uicontrol('Style', 'Text', 'String','Name:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 16.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_bhkw);
handles.btext.bpower= uicontrol('Style', 'Text', 'String','Power el. [kW]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 14.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_bhkw);
% handles.btext.bthreshold= uicontrol('Style', 'Text', 'String','Threshold:',...
%     'units', 'characters', ...
%     'HorizontalAlignment', 'left', ...
%     'Position', [1.5 12.5 + y_offset 15 1.6153], ...
%     'parent', handles.frame1_bhkw);
handles.btext.beta= uicontrol('Style', 'Text', 'String','eta el. [100 %]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 10.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_bhkw);
handles.btext.beta_therm= uicontrol('Style', 'Text', 'String','eta th. [100 %]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 8.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_bhkw);

%Editfields for values of variables

% BHKW ID
handles.b_edit.bid= uicontrol('Style', 'Text', 'String',handles.b_id_select,...
    'units', 'characters', ...
    'Position', [20 18.5 + y_offset 15 1.6153],...
    'BackgroundColor',[0.941 0.941 0.941], ...
    'parent', handles.frame1_bhkw);
% BHKW Name
handles.b_edit.b_name= uicontrol('Style', 'Edit', 'String', ...
    char(handles.workspace.plant.getCHPName(handles.b_id_select)),...
    'units', 'characters', ...
    'Position', [20 16.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_bhkw);
% Power
handles.b_edit.b_power= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getCHPParam(handles.b_id_select, 'Pel'),...
    'units', 'characters', ...
    'Position', [20 14.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_bhkw, ...
    ...'ToolTipString', 'Geben Sie hier die Leitung des BHKWs ein!');
    'ToolTipString', 'Please specify the maximal electrical power of the chp!');

% Threshold
% handles.b_edit.b_threshold= uicontrol('Style', 'Edit', 'String', ...
%     handles.workspace.plant.bhkw.(handles.b_id_select).threshold,...
%     'units', 'characters', ...
%     'Position', [20 12.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
%     'parent', handles.frame1_bhkw);
% eta
handles.b_edit.b_eta= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getCHPParamD(handles.b_id_select, 'eta_el'),...
    'units', 'characters', ...
    'Position', [20 10.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_bhkw, ...
    ...'ToolTipString', 'Geben Sie hier den Wirkungsgrad des BHKW ein!');
    'ToolTipString', 'Please specify the level of electrical efficiency of the chp!');

handles.b_edit.b_eta_therm= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getCHPParamD(handles.b_id_select, 'eta_therm'),...
    'units', 'characters', ...
    'Position', [20 8.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_bhkw, ...
    ...'ToolTipString', 'Geben Sie hier den Wirkungsgrad des BHKW ein!');
    'ToolTipString', 'Please specify the level of thermal efficiency of the chp!');


%%

if isfield(handles, 'b_but')
  if isfield(handles.b_but, 'bhkwsave')
    if ishandle(handles.b_but.bhkwsave)
        delete(handles.b_but.bhkwsave);
    end
    handles.b_but= rmfield(handles.b_but, 'bhkwsave');
  end

  if isfield(handles.b_but, 'bhkwcancel')
    if ishandle(handles.b_but.bhkwcancel)
        delete(handles.b_but.bhkwcancel);
    end
    handles.b_but= rmfield(handles.b_but, 'bhkwcancel');
  end

  if isfield(handles.b_but, 'bhkwreset')
    if ishandle(handles.b_but.bhkwreset)
        delete(handles.b_but.bhkwreset);
    end
    handles.b_but= rmfield(handles.b_but, 'bhkwreset');
  end

  handles= rmfield(handles, 'b_but');
end


% handles.frame2= uipanel(...
%     'units', 'characters', ...
%     'Position', [1.5 2.5 50 6], ...
%     'parent', handles.frame1);
handles.b_but.bhkwsave= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_bhkwsave_but_Callback,...
    'units', 'characters', ...
    ...%'Position', [20 7.0 15 1.6153],'String','OK', ...
    ...'Position', [60 18.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 1.7 13.8 1.6153], ...
    'String','OK', ...
    'parent', handles.frame1_bhkw, ...
    'userdata', 1);

handles.b_but.bhkwcancel= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_bhkwsave_but_Callback,...
    'units', 'characters', ...
    ...'Position', [60 16.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 + 13.8 + 0.5 1.7 13.8 1.6153], ...
    'String','Cancel', ...
    'parent', handles.frame1_bhkw, ...
    'userdata', 0);

handles.b_but.bhkwreset= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_bhkwsave_but_Callback,...
    'units', 'characters', ...
    ...'Position', [60 14.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 + 2*(13.8 + 0.5) 1.7 13.8 1.6153], ...
    'String','Reset', ...
    'parent', handles.frame1_bhkw, ...
    'userdata', 2);

% Update handles structure
guidata(hObject, handles);

%%


