%% cmdEditPump_Callback
% Callback of button cmdEditPump of <gui_plant.html |gui_plant|>
%
function cmdEditPump_Callback(hObject, eventdata, handles)
%% Release: 1.8

% hObject    handle to cmdEditPump (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

%%

error( nargchk(3, 3, nargin, 'struct') );
error( nargoutchk(0, 0, nargout, 'struct') );

%%

checkArgument(handles, 'handles', 'struct', '3rd');

%%
%get selected pump
handles.p_id_active= get(handles.listPumps, 'value');
handles.p_id_select= ...
    char(handles.workspace.plant.getPumpID(handles.p_id_active));
  
%%  
%prevent change of pump, bhkw or fermenter during editing
handles= gui_plant_enable_elements(handles, 'off');    


%%

pos_frmPlC= get(handles.frmPlantControl, 'Position');

y_offset= 11.05;

if ~isfield(handles, 'frame1_pump')
  %create Frame for pump variables
  handles.frame1_pump= uipanel('Title', 'Edit Pumps', ...
    'units', 'characters', ...
    'Position', [57.8 pos_frmPlC(2) 76.2 pos_frmPlC(4)]);
end

set(handles.frame1_pump,'Visible','on');

%texts
handles.ptext.pid= uicontrol('Style', 'Text', 'String','pump ID:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 18.5 + y_offset 15 1.6153],'HandleVisibility','on', ...
    'parent', handles.frame1_pump);
% handles.ptext.pdestinyID= uicontrol('Style', 'Text', 'String','destiny ID:',...
%     'units', 'characters', ...
%     'HorizontalAlignment', 'left', ...
%     'Position', [1.5 16.5 + y_offset 15 1.6153], ...
%     'parent', handles.frame1_pump);
handles.ptext.phlift= uicontrol('Style', 'Text', 'String','lift height [m]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 14.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_pump);
handles.ptext.pdhorz= uicontrol('Style', 'Text', 'String','dist. horiz. [m]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 12.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_pump);
handles.ptext.peta= uicontrol('Style', 'Text', 'String','eta [100 %]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 10.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_pump);
handles.ptext.pmu= uicontrol('Style', 'Text', 'String','mu [100 %]:',...
    'units', 'characters', ...
    'HorizontalAlignment', 'left', ...
    'Position', [1.5 8.5 + y_offset 15 1.6153], ...
    'parent', handles.frame1_pump);

%Editfields for values of variables

% pump ID
handles.p_edit.pid= uicontrol('Style', 'Text', 'String',handles.p_id_select,...
    'units', 'characters', ...
    'Position', [20 18.5 + y_offset 25 1.6153],...
    'BackgroundColor',[0.941 0.941 0.941], ...
    'parent', handles.frame1_pump);
% pump Name
% handles.p_edit.pdestinyid= uicontrol('Style', 'Edit', 'String', ...
%     char(handles.workspace.plant.getCHPName(handles.b_id_select)),...
%     'units', 'characters', ...
%     'Position', [20 16.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
%     'parent', handles.frame1_bhkw);
% Power
handles.p_edit.phlift= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getPumpParam(handles.p_id_select, 'h_lift'),...
    'units', 'characters', ...
    'Position', [20 14.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_pump, ...
    'ToolTipString', 'Please specify the lifting height of the pump!');

handles.p_edit.pdhorz= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getPumpParam(handles.p_id_select, 'd_horizontal'),...
    'units', 'characters', ...
    'Position', [20 12.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_pump, ...
    'ToolTipString', 'Please specify the horizontal distance of the pump!');

% Threshold
% handles.b_edit.b_threshold= uicontrol('Style', 'Edit', 'String', ...
%     handles.workspace.plant.bhkw.(handles.b_id_select).threshold,...
%     'units', 'characters', ...
%     'Position', [20 12.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
%     'parent', handles.frame1_bhkw);
% eta
handles.p_edit.peta= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getPumpParamD(handles.p_id_select, 'eta'),...
    'units', 'characters', ...
    'Position', [20 10.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_pump, ...
    ...'ToolTipString', 'Geben Sie hier den Wirkungsgrad des BHKW ein!');
    'ToolTipString', 'Please specify the level of electrical efficiency of the pump!');

handles.p_edit.pmu= uicontrol('Style', 'Edit', 'String', ...
    handles.workspace.plant.getPumpParamD(handles.p_id_select, 'mu'),...
    'units', 'characters', ...
    'Position', [20 8.5 + y_offset 15 1.6153],'BackgroundColor','white', ...
    'parent', handles.frame1_pump, ...
    ...'ToolTipString', 'Geben Sie hier den Wirkungsgrad des BHKW ein!');
    'ToolTipString', 'Please specify the coefficient of friction of the pump!');


%%

if isfield(handles, 'p_but')
  if isfield(handles.p_but, 'pumpsave')
    if ishandle(handles.p_but.pumpsave)
        delete(handles.p_but.pumpsave);
    end
    handles.p_but= rmfield(handles.p_but, 'pumpsave');
  end

  if isfield(handles.p_but, 'pumpcancel')
    if ishandle(handles.p_but.pumpcancel)
        delete(handles.p_but.pumpcancel);
    end
    handles.p_but= rmfield(handles.p_but, 'pumpcancel');
  end

  if isfield(handles.p_but, 'pumpreset')
    if ishandle(handles.p_but.pumpreset)
        delete(handles.p_but.pumpreset);
    end
    handles.p_but= rmfield(handles.p_but, 'pumpreset');
  end

  handles= rmfield(handles, 'p_but');
end


% handles.frame2= uipanel(...
%     'units', 'characters', ...
%     'Position', [1.5 2.5 50 6], ...
%     'parent', handles.frame1);
handles.p_but.pumpsave= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_pumpsave_but_Callback,...
    'units', 'characters', ...
    ...%'Position', [20 7.0 15 1.6153],'String','OK', ...
    ...'Position', [60 18.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 1.7 13.8 1.6153], ...
    'String','OK', ...
    'parent', handles.frame1_pump, ...
    'userdata', 1);

handles.p_but.pumpcancel= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_pumpsave_but_Callback,...
    'units', 'characters', ...
    ...'Position', [60 16.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 + 13.8 + 0.5 1.7 13.8 1.6153], ...
    'String','Cancel', ...
    'parent', handles.frame1_pump, ...
    'userdata', 0);

handles.p_but.pumpreset= uicontrol('Style','pushbutton', ...
    'CallBack',@gui_plant_pumpsave_but_Callback,...
    'units', 'characters', ...
    ...'Position', [60 14.5 + y_offset 13.8 1.6153],...
    'Position', [1.5 + 2*(13.8 + 0.5) 1.7 13.8 1.6153], ...
    'String','Reset', ...
    'parent', handles.frame1_pump, ...
    'userdata', 2);

% Update handles structure
guidata(hObject, handles);

%%


