%% gui_plant_f_buttongroup_cbk
% SelectionChange Callback of buttongroup on panel for fermenter on
% <gui_plant.html |gui_plant|> 
%
function gui_plant_f_buttongroup_cbk(hObject, eventdata)
%% Release: 1.1

%%

error( nargchk(2, 2, nargin, 'struct') );
error( nargoutchk(0, 0, nargout, 'struct') );

%%

handles= guidata(hObject);

%%

if ~isstruct(handles)
  error(['The parameter handles must be of type struct, ', ...
         'but is of type ', class(handles), '!']);
end

%%

y_offset= 2.85;

%%
% function uibuttongroup1_SelectionChangeFcn(hObject,eventdata)
switch get(eventdata.NewValue,'Tag') % Get Tag of selected object.
  case 'f_general'

    handles= gui_plant_createFermenterPanel(handles);

    % Update handles structure
    %guidata(hObject, handles);
    
  case 'f_inflow'

    %   handles.f_id_active=get(handles.listDigesters,'value');
    handles.f_id_select= ...
        char(handles.workspace.plant.getDigesterID(handles.f_id_active));
    %f_inflow= ...
     %   handles.workspace.plant.fermenter.(handles.f_id_select).inflow;

    %create Frame for Fermenter variables
    handles.frame1_2= uicontrol('Style', 'Frame',...
        'units', 'characters', ...
        'Position', [1.5 y_offset + 2 43.5 18.85], ...
        'ForegroundColor', [0.941 0.941 0.941], ...
        'parent', handles.frame1);
    %texts
    handles.ftext.f_inf_amount= uicontrol('Style', 'Text', ...
        'String','Amount:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 18.5 + y_offset 15 1.6153],...
        'HandleVisibility','on', 'parent', handles.frame1);
    handles.ftext.f_inf_pheight= uicontrol('Style', 'Text', ...
        'String','Liftingheight [m]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 16.5 + y_offset 16.5 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_distance= uicontrol('Style', 'Text', ...
        'String','Distance [m]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 14.5 + y_offset 15 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_mu= uicontrol('Style', 'Text', 'String','mu [-]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 12.5 + y_offset 15 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_power= uicontrol('Style', 'Text', ...
        'String','Power [kW]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 10.5 + y_offset 15 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_maxflow= uicontrol('Style', 'Text', ...
        'String','max. flow [m³/d]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 8.5 + y_offset 16.5 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_minflow= uicontrol('Style', 'Text', ...
        'String','min. flow [m³/d]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 6.5 + y_offset 16.5 1.6153], ...
        'parent', handles.frame1);
    handles.ftext.f_inf_eta= uicontrol('Style', 'Text', ...
        'String','eta [100 %]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 4.5 + y_offset 15 1.6153], ...
        'parent', handles.frame1);

      if(0) %% TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    %     %Editfields for values of variables
    %
    %% TODO
    %
    % s. bei gui_plant_createFermenterPanel bzw. unten wie man eingetragene
    % Werte speichert, damit die bei einem wechsel nicht gelöscht werden
    %
    % inflow weight
    handles.f_edit.f_inf_amount= uicontrol('Style', 'Edit', ...
        'String',f_inflow.amount,...
        'units', 'characters', ...
        'enable','off',...
        'Position', [20 18.5 + y_offset 25 1.6153],...
        'BackgroundColor','white', ...
        'parent', handles.frame1);
    % Pump liftingheight
    handles.f_edit.f_inf_liftheight= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.liftingheight,...
        'units', 'characters', ...
        'Position', [20 16.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
    ...'ToolTipString', 'Geben Sie hier die Förderhöhe der Pumpe ein!');
    'ToolTipString', 'Please specify the static head of the pump!');
    % distance
    handles.f_edit.f_inf_distance= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.distance,...
        'units', 'characters', ...
        'Position', [20 14.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier die Förderdistanz der Pumpe ein!');
'ToolTipString', 'Please specify the pump distance of the pump!');
    % mu
    handles.f_edit.f_inf_mu= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.mu,...
        'units', 'characters', ...
        'Position', [20 12.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier den Reibungskoeffizienten der Pumpstrecke ein!');
'ToolTipString', 'Please specify the coefficient of friction of the pump distance!');
    % Power
    handles.f_edit.f_inf_power= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.power,...
        'enable','off',...
        'units', 'characters', ...
        'Position', [20 10.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier die Leistung der Pumpe ein!');
'ToolTipString', 'Please specify the maximal power of the pump!');
    % maxflow
    handles.f_edit.f_inf_maxflow= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.maxflow,...
        'enable','off',...
        'units', 'characters', ...
        'Position', [20 8.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier die maximale Fördermenge der Pumpe ein!');
'ToolTipString', 'Please specify the maximal volumeflow of the pump!');
    % minflow
    handles.f_edit.f_inf_minflow= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.minflow,...
        'enable','off',...
        'units', 'characters', ...
        'Position', [20 6.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier die minimale Fördermenge der Pumpe ein!');
'ToolTipString', 'Please specify the minimal volumeflow of the pump!');
    % eta
    handles.f_edit.f_inf_eta= uicontrol('Style', 'Edit', ...
        'String',f_inflow.pump.eta,...
        'units', 'characters', ...
        'Position', [20 4.5 + y_offset 25 1.6153],'BackgroundColor','white', ...
        'parent', handles.frame1, ...
...'ToolTipString', 'Geben Sie hier den Wirkungsgrad der Pumpe ein!');
'ToolTipString', 'Please specify the level of efficiency of the pump!');

      end

    %%

    handles= ...
        gui_plant_createFermenterBtnGroup(handles, 2);

    %create Frame for buttons
%         handles.frame2_2= uicontrol('Style', 'Frame',...
%             'Position', [320 15 200 65]);
%         handles.f_but.fermsave_2= uicontrol('Style','pushbutton', ...
%             'CallBack',@fermsave_but_Callback,...
%             'Position', [445 25 69 22],'String','Save');
%         
%         % Create the button group.
%         handles.fbuttons_2 = uibuttongroup('visible','off', ...
%             'Position',[0.55 0.08 0.4 0.15]);
%         handles.f_but.fermgeneral= uicontrol('Style','togglebutton',...
%             'Position', [15 15 50 22],'String','general','Max',1, ...
%             'Min',0,'Tag','f_general',...
%             'parent',handles.fbuttons_2,'HandleVisibility','off');
%         %set(handles.f_but.fermgeneral,'Value',1);
%         handles.f_but.ferminflow= uicontrol('Style','togglebutton',...
%             'Position', [75 15 50 22],'String','inflow','Max',1, ...
%             'Min',0,'Tag','f_inflow',...
%             'parent',handles.fbuttons_2,'HandleVisibility','off');
%         handles.f_but.fermheating= uicontrol('Style','togglebutton',...
%             'Position', [135 15 50 22],'String','heating','Max',1, ...
%             'Min',0,'Tag','f_heating',...
%             'parent',handles.fbuttons_2,'HandleVisibility','off');
%         
%         % Initialize some button group properties.
%         set(handles.fbuttons_2,'SelectionChangeFcn',@f_buttongroup_cbk);
%         % inflow
%         set(handles.fbuttons_2,'SelectedObject',handles.f_but.ferminflow); 
%         set(handles.fbuttons_2,'Visible','on');

  case 'f_heating'
    %handles.f_id_active=get(handles.listDigesters,'value');
    handles.f_id_select= ...
        char(handles.workspace.plant.getDigesterID(handles.f_id_active));
    %f_heat= ...
     %   handles.workspace.plant.fermenter.(handles.f_id_select).heating;

    %create Frame for Fermenter variables
    handles.frame1_3= uicontrol('Style', 'Frame',...
        'units', 'characters', ...
        'Position', [1.5 y_offset + 2 43.5 18.85],...%17.85
        'ForegroundColor', [0.941 0.941 0.941], ...
        'parent', handles.frame1);
    %texts
    handles.ftext.f_heat_eta= uicontrol('Style', 'Text', 'String','eta el. [100 %]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 18.5 + y_offset 15 1.6153],...
        'HandleVisibility','on', 'parent', handles.frame1);
    handles.ftext.f_heat_hth= uicontrol('Style', 'Text', 'String','h_th [W/(m² K)]:',...
        'units', 'characters', ...
        'HorizontalAlignment', 'left', ...
        'Position', [1.5 16.5 + y_offset 17 1.6153], ...
        'parent', handles.frame1);

    %     %Editfields for values of variables
    %
    % heating eta
    
    if isfield(handles.f_edit, 'f_heat_eta')
      text= get(handles.f_edit.f_heat_eta, 'String');
    else
      text= handles.workspace.plant.getDigesterParamD(handles.f_id_select, 'eta');
    end

    handles.f_edit.f_heat_eta= uicontrol('Style', 'Edit', ...
        'String',text,...
        'units', 'characters', ...
        'Position', [20 18.5 + y_offset 25 1.6153],...
        'BackgroundColor','white', ...
        'parent', handles.frame1, ...
        ...'ToolTipString', 'Geben Sie hier den Wirkungsgrad der Heizung ein!');
        'ToolTipString', 'Please specify the level of el. efficiency of the heating!');
      
    %%
    % heating hth
    
    if isfield(handles.f_edit, 'f_heat_hth')
      text= get(handles.f_edit.f_heat_hth, 'String');
    else
      text= handles.workspace.plant.getDigesterParam(handles.f_id_select, 'h_th');
    end
    
    handles.f_edit.f_heat_hth= uicontrol('Style', 'Edit', ...
        'String',text,...
        'units', 'characters', ...
        'Position', [20 16.5 + y_offset 25 1.6153],...
        'BackgroundColor','white', ...
        'parent', handles.frame1, ...
        'ToolTipString', 'Edit the heat transfer coefficient of the fermenter!');


    %%


    %%

    handles= ...
        gui_plant_createFermenterBtnGroup(handles, 3);

    %%

    %create Frame for buttons
%         handles.frame2_3= uicontrol('Style', 'Frame',...
%             'Position', [320 15 200 65]);
%         handles.f_but.fermsave_3= uicontrol('Style','pushbutton', ...
%             'CallBack',@fermsave_but_Callback,...
%             'Position', [445 25 69 22],'String','Save');
%         
%         % Create the button group.
%         handles.fbuttons_3 = uibuttongroup('visible','off', ...
%             'Position',[0.55 0.08 0.4 0.15]);
%         handles.f_but.fermgeneral= uicontrol('Style','togglebutton',...
%             'Position', [15 15 50 22],'String','general','Max',1, ...
%             'Min',0,'Tag','f_general',...
%             'parent',handles.fbuttons_3,'HandleVisibility','off');
%         handles.f_but.ferminflow= uicontrol('Style','togglebutton',...
%             'Position', [75 15 50 22],'String','inflow','Max',1, ...
%             'Min',0,'Tag','f_inflow',...
%             'parent',handles.fbuttons_3,'HandleVisibility','off');
%         handles.f_but.fermheating= uicontrol('Style','togglebutton',...
%             'Position', [135 15 50 22],'String','heating','Max',1, ...
%             'Min',0,'Tag','f_heating',...
%             'parent',handles.fbuttons_3,'HandleVisibility','off');
%         
%         % Initialize some button group properties.
%         set(handles.fbuttons_3,'SelectionChangeFcn',@f_buttongroup_cbk);
%         % heating activated
%         set(handles.fbuttons_3,'SelectedObject',handles.f_but.fermheating);  
%         set(handles.fbuttons_3,'Visible','on');
      % Continue with more cases as necessary.
      
  otherwise
    % Code for when there is no match.
    
end

% Update handles structure
guidata(hObject, handles);

%%


