%% pn_createNetworkPanel
% Creates the panel of the <gui_plant_network.html gui_plant_network>
%
function handles= pn_createNetworkPanel(handles)
%% Release: 1.7

%%

error( nargchk(1, 1, nargin, 'struct') );
error( nargoutchk(1, 1, nargout, 'struct') );

%%

checkArgument(handles, 'handles', 'struct', '1st');

%%

plant= handles.plant;
plant_network= handles.plant_network;

n_fermenter= handles.plant.getNumDigestersD();

if sum( abs( [n_fermenter, n_fermenter + 1] - size(plant_network) ) ) ~= 0

  errordlg('The load plant_network has not the correct dimension!');

  set(handles.lblPath,     'String', '');
  set(handles.lblFilename, 'String', '');

  return;
    
end

handles.lblFermenterIn= zeros(n_fermenter + 1, 1);
handles.lblFermenterOut= zeros(n_fermenter, 1);
handles.togConnect= zeros(n_fermenter, n_fermenter + 1);

btn_height= 2;%1.615
offset= -0.385;

%%

for ifermenter= 1:n_fermenter

  handles.lblFermenterIn(ifermenter, 1)= ...
      uicontrol('Style', 'Text', ...
      'String', char(plant.getDigesterName(ifermenter)),...
      'units', 'characters', ...
      'HorizontalAlignment', 'center', ...
      'Position', [25.8 + 16.2*(ifermenter - 1) 17.5 + offset 16.2 btn_height], ...
      'parent', handles.panNetwork);

  handles.lblFermenterOut(ifermenter, 1)= ...
      uicontrol('Style', 'Text', ...
      'String', char(plant.getDigesterName(ifermenter)),...
      'units', 'characters', ...
      'HorizontalAlignment', 'left', ...
      'Position', [7.6 15.385 + offset - btn_height*(ifermenter - 1) ...
                   18.2 btn_height], ...
      'parent', handles.panNetwork);

  %%
  
  for ifermenterIn= 1:n_fermenter + 1

    handles.togConnect(ifermenter, ifermenterIn)= ...
        uicontrol('Style', 'togglebutton', ...
        'String', 'Disconnected',...
        'units', 'characters', ...
        'HorizontalAlignment', 'center', ...
        'Position', ...
        [25.8 + 16.2*(ifermenterIn - 1) ...
         15.385 - btn_height*(ifermenter - 1) + offset ...
         16.2 btn_height], ...
        'parent', handles.panNetwork, ...
        'value', plant_network(ifermenter,ifermenterIn) > 0, ...
        'Callback', @pn_togConnectCallback);

    if ifermenter == ifermenterIn

      set(handles.togConnect(ifermenter, ifermenterIn), ...
          'enable', 'off');

    end

    %%
    
    if plant_network(ifermenter,ifermenterIn)

      set(handles.togConnect(ifermenter, ifermenterIn), ...
          'String', 'Connected');

      %%
      
      if ifermenterIn <= n_fermenter

        set(handles.togConnect(ifermenter, ifermenterIn), ...
        'ToolTipString', ...
        sprintf('Click to disconnect output of %s from input of %s!', ...
        char(plant.getDigesterName(ifermenter)), ...
        char(plant.getDigesterName(ifermenterIn))));

      else

        set(handles.togConnect(ifermenter, ifermenterIn), ...
        'ToolTipString', ...
        sprintf('Click to disconnect output of %s from input of %s!', ...
        char(plant.getDigesterName(ifermenter)), ...
        'Endlager'));

      end

    else

      %%
      
      if ifermenterIn <= n_fermenter

        set(handles.togConnect(ifermenter, ifermenterIn), ...
        'ToolTipString', ...
        sprintf('Click to connect output of %s with input of %s!', ...
        char(plant.getDigesterName(ifermenter)), ...
        char(plant.getDigesterName(ifermenterIn))));

      else

        set(handles.togConnect(ifermenter, ifermenterIn), ...
        'ToolTipString', ...
        sprintf('Click to connect output of %s with input of %s!', ...
        char(plant.getDigesterName(ifermenter)), ...
        'Endlager'));

      end

    end

  end
    
end

%%

handles.lblFermenterIn(n_fermenter + 1, 1)= ...
        uicontrol('Style', 'Text', ...
        'String', 'Endlager',...
        'units', 'characters', ...
        'HorizontalAlignment', 'center', ...
        'Position', [25.8 + 16.2*(n_fermenter) 17.5 + offset 16.2 btn_height], ...
        'parent', handles.panNetwork);
    
%%

set(handles.lblInput, 'Position', [25.8 18.846 + offset ...
                                   16.2*(n_fermenter + 1) btn_height]);

set(handles.lblOutput, 'Position', ...
    [1.2 17.5 + offset - btn_height*(n_fermenter) - 0.3 - 0.451 ...
     6.6 btn_height*(n_fermenter) + btn_height + 0.4 + 0.451]);

set(handles.frmPlantNetwork, 'visible', 'on');
set(handles.frmPlantNetwork, 'Position', ...
    [7.1 17.5 + offset - btn_height*(n_fermenter) - 0.3 - 0.451 ...
     18.2 + 16.2*(n_fermenter + 1) + 0.7 ...
     btn_height*(n_fermenter) + btn_height + 0.4 + 0.451]);

%%

set(handles.cmdSave, 'enable', 'on');

%%


